version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./www:/var/www

### PHP-FPM Container #######################################

    php-fpm7:
      build:
        context: ./php7
      volumes:
        - /home/code/offical.com:/var/www/offical.com
      expose:
        - "9000"
      depends_on:
        - mysql

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - /home/code/offical.com:/var/www/offical.com
          - /home/code/hngaole.cn:/var/www/hngaole.cn
          - /home/code/hunangaole.cn:/var/www/hunangaole.cn
          - /home/code/mmiying.com:/var/www/mmiying.com
          - /home/code/qingzhi:/var/www/qingzhi
          - /home/code/shanin:/var/www/shanin
          - /home/code/ssl
      ports:
          - "80:80"
      depends_on:
          - php-fpm7

### MySQL Container #########################################

    mysql:
      image: mysql:5.6
      volumes:
        - /home/code/offical.com:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456

### Volumes Setup ###########################################

volumes:
    mysql-data:
