version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./www:/var/www

### PHP-FPM Container #######################################

    php-fpm7:
      build:
        context: ./php7
      volumes:
        - /home/code/offical.com:/var/www/offical.com
      expose:
        - "9000"
      depends_on:
        - mysql

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - /home/code/offical.com:/var/www/offical.com
          - /home/code/hngaojia.cn:/var/www/hngaojia.cn
          - /home/code/hunangaole.cn:/var/www/hunangaole.cn
          - /home/code/mmiying.com:/var/www/mmiying.com
          - /home/code/qingzhi:/var/www/qingzhi
          - /home/code/shanin:/var/www/shanin
          - /home/code/onesite:/var/www/onesite
          - /home/code/ssl:/home/code/ssl
          - /home/code/conf:/etc/nginx/conf.d
          - /home/code/nginx_log:/var/www/nginx_log
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - php-fpm7

### MySQL Container #########################################

    mysql:
      image: mysql:5.6
      volumes:
        - /home/code/offical.com:/var/lib/mysql
        - /home/code/sql:/home/code/sql
      ports:
        - "3316:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456

### Volumes Setup ###########################################

volumes:
    mysql-data:
