version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./www:/var/www

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php
      volumes:
        - E:\site\offical.com:/var/www/
      expose:
        - "9888"
      depends_on:
        - mysql

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - E:\site\offical.com:/var/www/
      ports:
          - "80:80"
      depends_on:
          - php-fpm

### MySQL Container #########################################

    mysql:
      image: mysql:5.6
      volumes:
        - E:\site\1sql\offical.com:/var/lib/mysql
      ports:
        - "3316:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456

### Volumes Setup ###########################################

volumes:
    mysql-data:
